# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [9]:
# 1 
arr = np.random.random_integers(1,20,(5,5))

print(arr)



[[11 14  6 14 18]
 [19  1  8 11 16]
 [ 9  1 11  3  2]
 [13  8 16 17  8]
 [13  3 20  5 11]]


C:\Users\PMYLS\AppData\Local\Temp\ipykernel_10896\3651830437.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 20 + 1) instead
  arr = np.random.random_integers(1,20,(5,5))


In [12]:
arr[:,2] = 1

In [13]:
arr

array([[11, 14,  1, 14, 18],
       [19,  1,  1, 11, 16],
       [ 9,  1,  1,  3,  2],
       [13,  8,  1, 17,  8],
       [13,  3,  1,  5, 11]], dtype=int32)

In [20]:
### 2 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr1 = np.arange(1,17).reshape((4,4))
print(arr1)
arr1[0][0]=0
arr1[1][1]=0
arr1[2][2]=0
arr1[3][3]=0
print('*'*30)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
******************************
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [28]:
np.fill_diagonal(arr1,0)

In [29]:
arr1 = np.arange(1,17).reshape((4,4))
print('Array:\n',arr1)

# Replace the diagonal elements with 0
np.fill_diagonal(arr1, 0)
print("Modified array:")
print(arr1)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [40]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

array = np.arange(1,37).reshape(6,6)
print('Original Array:\n\n',array)

sub_array = array[2:4,1:3]
print('\n Sub Array:\n',sub_array)

Original Array:

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

 Sub Array:
 [[14 15]
 [20 21]]


In [53]:
## 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
array = np.random.randint(1,100,(4,4))
print('Array:\n',array)
print('Extracted elements border')
print(array[0,:])
print(array[1,::3])
print(array[2,::3])
print(array[3,:])

Array:
 [[ 1 41 43 34]
 [52 37 20  7]
 [35 97 48 46]
 [46 52 65 84]]
Extracted elements border
[ 1 41 43 34]
[52  7]
[35 46]
[46 52 65 84]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [ ]:
## 1. Create two NumPy arrays of shape (3, 4) filled with random integers.
# Perform element-wise addition, subtraction, multiplication, and division.

array1 = np.random.randint(1,20,(3,4))
array2 = np.random.randint(21,40,(3,4))


print('Array1:\n',array1)
print('Array2:\n',array2)

print('-----Element wise Arthmatic Operation-------')

print('Addition')
print(array1 + array2)

print('Subtraction')
print(array1 - array2)

print('Multiplication')
print(array1 * array2)

print('Division')
print(array1 / array2)

Array1:
 [[16 16  8  2]
 [ 4  8  7  4]
 [13 11  5 16]]
Array2:
 [[23 26 33 23]
 [39 24 39 35]
 [28 26 32 26]]
-----Element wise Arthmatic Operation-------
Addition
[[39 42 41 25]
 [43 32 46 39]
 [41 37 37 42]]
Subtraction
[[ -7 -10 -25 -21]
 [-35 -16 -32 -31]
 [-15 -15 -27 -10]]
Multiplication
[[368 416 264  46]
 [156 192 273 140]
 [364 286 160 416]]
Division
[[0.69565217 0.61538462 0.24242424 0.08695652]
 [0.1025641  0.33333333 0.17948718 0.11428571]
 [0.46428571 0.42307692 0.15625    0.61538462]]


In [70]:
## 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
array3 = np.arange(1,17).reshape(4,4)
print(array3)
print('\nRow wise addition')
print(np.sum(array3,axis=0))

print('\nColumn wise addtion')
print(np.sum(array3,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row wise addition
[28 32 36 40]

Column wise addtion
[10 26 42 58]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [74]:
new_arr = np.random.randint(1,26,(5,5))
print(new_arr)
print(np.mean(new_arr))
print(np.median(new_arr))
print(np.var(new_arr))
print(np.std(new_arr))



[[25 23  1 21 21]
 [13 25 23 22  3]
 [12 25 21 17  6]
 [22 21  1  8  1]
 [21 20  2 18 17]]
15.56
20.0
71.3664
8.44786363526306


In [76]:
arr = np.arange(1,10).reshape(3,3)
scaled_arr = (arr - np.mean(arr))/np.std(arr)
print(arr)
print(scaled_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [ ]:
## 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of 
#     the 2D array using broadcasting.


a = np.random.randint(1,9,(3,3))
print('First array shape is: 3x3')
print(a)
b = np.random.randint(1,10,3)
print('Second array shape is: 1x3')
print(b)

## broadcasting 
print('Third array shape is:3x3')
print(a+b)


First array shape is: 3x3
[[7 7 1]
 [1 1 1]
 [7 4 3]]
Second array shape is: 1x3
[1 9 1]
Third array shape is:3x3
[[ 8 16  2]
 [ 2 10  2]
 [ 8 13  4]]


In [8]:
## 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,)
#     from each column of the 2D array using broadcasting.


array1 = np.random.randint(1,10,(4,4))
array2 = np.random.randint(1,10,4)

print('First array of shape: ',array1.shape)
print(array1)


print('Second array of shape: ',array2.shape)
print(array2)

broatcast_array = array1 + array2
print('Broadcsted array',broatcast_array.shape)
print(broatcast_array)

First array of shape:  (4, 4)
[[6 4 9 5]
 [6 7 1 8]
 [1 7 2 8]
 [3 6 2 1]]
Second array of shape:  (4,)
[1 6 9 3]
Broadcsted array (4, 4)
[[ 7 10 18  8]
 [ 7 13 10 11]
 [ 2 13 11 11]
 [ 4 12 11  4]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [17]:
## 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
array = np.random.randint(1,20,(3,3))
print('Matrix')
print(array)


print('\nDeterminent:\n',np.linalg.det(array))
print('\nInverse:\n',np.linalg.inv(array))
print('\nEigenvalues:\n',np.linalg.eigvals(array))


Matrix
[[12 17  2]
 [ 7 18  1]
 [12 19 14]]

Determinent:
 1168.0000000000002

Inverse:
 [[ 0.1994863  -0.17123288 -0.01626712]
 [-0.07363014  0.12328767  0.00171233]
 [-0.07106164 -0.02054795  0.08304795]]

Eigenvalues:
 [29.08248733  3.52538382 11.39212886]


In [24]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
print('Array 1:')
print(a)

print('\nArray 2:')
print(b)

print('\nDot Product')
print(np.dot(a,b))

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Dot Product
[[ 58  64]
 [139 154]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random

In [ ]:
# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

a = np.arange(1,10).reshape(3,3)
print('Array a is:\n')
print(a)
print(a.shape)

reshaped_a = a.reshape((1,9))
print('Reshaped array a is:\n')
print(reshaped_a)
print(reshaped_a.shape)

Array a is:

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
Reshaped array a is:

[[1 2 3 4 5 6 7 8 9]]
(1, 9)


In [38]:
# 2. Create a NumPy array of shape (5, 5) filled with random

random_array = np.random.random((5,5))
print(random_array)
print(random_array.shape)

[[0.53169425 0.82351089 0.97989693 0.08806666 0.21191154]
 [0.67449858 0.51732815 0.00533439 0.92065011 0.11389754]
 [0.72215846 0.01040635 0.68339945 0.63247453 0.95466436]
 [0.11106369 0.4397195  0.94666721 0.94992652 0.13267345]
 [0.45921928 0.92790942 0.55386272 0.77920621 0.92937207]]
(5, 5)


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [46]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. 
#    Use fancy indexing to extract the elements at the corners of the array.

arr = np.random.randint(1,10,size=(5,5))
print(arr)

## Fancy indexing
print('Fancy Indexing')
print(arr[[0,0,-1,-1],[0,-1,0,-1]])


[[4 3 6 9 5]
 [7 2 7 7 6]
 [2 1 2 1 1]
 [5 4 4 9 9]
 [3 7 6 7 8]]
Fancy Indexing
[4 5 3 8]


In [50]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. 
#     Use boolean indexing to set all elements greater than 10 to 10.

array = np.random.randint(1,50,(4,4))
print(array)

print('Boolean Indexing')
array[array>10]=10

print('Bool Indexed Array')
print(array)

[[15 42 27 15]
 [14  5 22 10]
 [14 35 23 43]
 [44 15 37 29]]
Boolean Indexing
Bool Indexed Array
[[10 10 10 10]
 [10  5 10 10]
 [10 10 10 10]
 [10 10 10 10]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



In [55]:
lis= [
    {'name':'shoaib','age':22,'gender':'male'},
    {'name':'tauseef','age':24,'gender':'male'},
    {'name':'mailika','age':20,'gender':'female'},
]

array = np.array(lis)

print(array)
# it is not completed

[{'name': 'shoaib', 'age': 22, 'gender': 'male'}
 {'name': 'tauseef', 'age': 24, 'gender': 'male'}
 {'name': 'mailika', 'age': 20, 'gender': 'female'}]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [57]:
# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. 
#     Compute the sum of the unmasked elements.

array = np.random.randint(1,17,(4,4))
print('Original Array')
print(array)

print('Masked Array')
print(array[array>10])

Original Array
[[10 14  4  7]
 [ 5  2  5  1]
 [15 11  2  5]
 [15  5  8  9]]
Masked Array
[14 15 11 15]


In [68]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. 
#    Replace the masked elements with the mean of the unmasked elements.

masked_array  = np.random.randint(1,10,(3,3))
print('Original Array')
print(masked_array)

diagnol_mask = masked_array.diagonal()
print(diagnol_mask)

# replace the masked element with the mean of unmasked element
print('Mean of Array:',np.mean(masked_array))
masked_array[[0,1,2],[0,1,2]] =np.mean(masked_array)

print(masked_array) 


Original Array
[[3 2 4]
 [7 7 6]
 [4 3 4]]
[3 7 4]
Mean of Array: 4.444444444444445
[[4 2 4]
 [7 4 6]
 [4 3 4]]
