## `Numpy`

* Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. 
* it helps you work efficiently with numbers, arrays, and mathematical operations in Python.
* Here we will cover basics of Numpy, focusing on arrays and vectorized operations

In [2]:
import numpy as np

In [3]:
## create arrays 

## create 1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
## to check the shape of array
print(arr1.shape)   # one rows 5 columns

(5,)


In [5]:
arr2 = np.array([1,2,3,4,5]).reshape(1,5)  # now it has 1 row and 5 columns
print(arr2)
print(arr2.shape)
print(type(arr2))

[[1 2 3 4 5]]
(1, 5)
<class 'numpy.ndarray'>


* if the opening bracket is 2 and closing bracket is also 2 this is known as 2 dimentional matrix

In [6]:
## 2-D arrays

arr1 = np.array([[1,2,3,4,5],[4,5,6,6,7]])
print(arr1)   # now it has two rows and 5 columns
print(arr1.shape)

[[1 2 3 4 5]
 [4 5 6 6 7]]
(2, 5)


arrays with `built in elements`

In [7]:
## how to convert a single dimentional array into 2-Dimentional array

arr1 = np.array([1,2,3,4,5])
arr1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

`In built function in numpy `

In [8]:
## np.one()

np.ones((2,4))  # it give all the element 1's 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
## np.zeros

np.zeros((2,3))   # it give all the element zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones_like(arr1)  # 

array([1, 1, 1, 1, 1])

In [11]:
## Identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`Some Important Features`

In [12]:
## Attribute of Numpy array

arr = np.array([[12,3,4,5],[32,33,12,1]])

print('Array:\n ',arr)
print('Shape: ',arr.shape)
print('Number of Dimention: ',arr.ndim)
print('Size(Num of elements): ',arr.size)
print('Data type: ',arr.dtype)
print('Item size (in bytes): ',arr.itemsize)

Array:
  [[12  3  4  5]
 [32 33 12  1]]
Shape:  (2, 4)
Number of Dimention:  2
Size(Num of elements):  8
Data type:  int64
Item size (in bytes):  8


`Numpy Vectorized Operations`

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,6,7])

## Element wise addition
print('Addition: ',arr1+arr2)
## Element wise Subtraction
print('Subtraction: ',arr1-arr2)
## Element wise Multiplication
print('Multiplication: ',arr1*arr2)
## Element wise Division
print('Division: ',arr1/arr2)


Addition:  [ 5  7  9 10 12]
Subtraction:  [-3 -3 -3 -2 -2]
Multiplication:  [ 4 10 18 24 35]
Division:  [0.25       0.4        0.5        0.66666667 0.71428571]


`Universal Function`
* Universal Function are some function that are applied to the entire array. 

In [14]:
## np.sqrt 
print(np.sqrt(arr1))

## sum
print(np.sum([3,4,5,5]))

## mean
print(np.mean(arr2))

## exponential

print(np.exp(arr1))


## sine value 
print(np.sin(arr1))


## natural log
print(np.log10(arr1))


[1.         1.41421356 1.73205081 2.         2.23606798]
17
5.6
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


### `Slicing Operation`
* Slicing and indexing operation can be perform to access the element from the array

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [16]:
## access 2 from arr1
arr1[1]

np.int64(2)

In [17]:
arr = np.array([[2,3,41,31,4],[5,3,11,2,33],[6,4,3,6,2]])
print(arr)

[[ 2  3 41 31  4]
 [ 5  3 11  2 33]
 [ 6  4  3  6  2]]


In [18]:
# access 11 from arr
arr[1][2]

np.int64(11)

In [19]:
# access the 2nd row
arr[1]

array([ 5,  3, 11,  2, 33])

In [20]:
# access 11  2   3  6 

arr[1:,2:4]

array([[11,  2],
       [ 3,  6]])

`Modifying Elements`

In [21]:
arr[0] = 1000

In [22]:
arr

array([[1000, 1000, 1000, 1000, 1000],
       [   5,    3,   11,    2,   33],
       [   6,    4,    3,    6,    2]])

## `Practical Knowledge`
`Statistical Knowledge`

1. Normalization

In [23]:
## change data mean of 0 and std to 1 
data = np.array([1,2,3,4,5])

mean = np.mean(data)

std = np.std(data)

# Normalize the data
normalized_data = (data-mean)/std

print('Normalized data',normalized_data)

Normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [24]:
data = np.array([1,2,3,4,5])

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)

print(mean)
print(median)
print(variance)

3.0
3.0
2.0


`Logical Operation`

In [25]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
## to access all the element that are > than 5 
data[data>5]

array([ 6,  7,  8,  9, 10])

In [29]:
data[(data<5) | (data>9)]

array([ 1,  2,  3,  4, 10])