# Numpy with detail part-1

In [1]:
import numpy as np

In [2]:
# Numpy array has a fixed size
# while python list has a dynamic size when it size become complete then its size become increased
# Changing the size of ndarray create the new array and delete the existing array
#The element in the numpy array must be same data types while in list you can put different types of values
#

### Creating numpy array

## 1st method to create array

In [3]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
b=np.array([[1,3,4,],[5,6,7]])
b

array([[1, 3, 4],
       [5, 6, 7]])

In [14]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# for making the element float 
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# for making the element bool 
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [17]:
# for making the element complex 
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

## 2nd method to create an array

In [19]:
# np.arange

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
# With arange function we mostly used reshpe function


In [22]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## 3rd method to create an array

In [26]:
# np.ones and np.zeros

# These two function are basically used to inititalze the array


np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# np.random
# it is also used for the initialization

np.random.random((3,4))

array([[0.56602811, 0.10656456, 0.84424431, 0.42510373],
       [0.02255024, 0.05405607, 0.79540202, 0.34532305],
       [0.542026  , 0.85327088, 0.35360068, 0.63102387]])

## 4th method for array creation

In [32]:
# np.linspace(linear space)
# it generate points in the equal distance between points in the given range


np.linspace(-10,10,10)



array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

## 5th method to create an array

In [33]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
a=np.arange(16).reshape(2,2,2,2)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [5]:
a[1,0,1,1]

11

In [8]:
a[0,0,0,1]

1

In [9]:
a[1,0,1,1]

11

In [10]:
a[1,1,1,0]

14

#  5 important attribute

#### ndim

In [35]:
# every numpy array has a numpy class objects .it has basically the ability to 
# access the attributes of numpy class 

In [41]:
a1=np.arange(10) # array
a2=np.arange(12,dtype=float).reshape(3,4) # metrix
a3=np.arange(8).reshape(2,2,2)  # tensor


In [42]:
# ndim

In [44]:
# ndim stands for number of dimention
# by using this attribute you can find the dimention of every numpy array
a1.ndim

1

In [45]:
a2.ndim

2

In [46]:
a3.ndim

3

In [47]:
# shape

In [48]:
# shape tell you the items in each dimentions (how many rows and how many couumns)
a1.shape

(10,)

In [49]:
a2.shape

(3, 4)

In [51]:
print(a3)
a3.shape

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


(2, 2, 2)

In [54]:
# (2,2,2) ==>  the first element in the tupple tell you how many 2d array in your array then second 
# one tell you then number of rows and columns in each dimention 



In [55]:
# size

# it give you the total number of element in the array

In [56]:
a1.size

10

In [57]:
a2.size

12

In [58]:
a3.size

8

In [60]:
# itemsize 

# it tell you the size that  each item occupy in memory

In [62]:
a1.itemsize

4

In [63]:
a2.itemsize

8

In [64]:
a3.itemsize

4

In [65]:
# int32 will take 4 byte and int64 will take 8 byte

In [68]:
# dtype

# it tell you the datatype of your all items 

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing datatype

In [75]:
a3.astype(np.int)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [82]:
a2.astype(np.int64)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int64)

In [81]:
a2.itemsize

8

## Array Operations

In [85]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [86]:
# Now we will perform two type of operation one is scalar operation and the other one is vector operation

In [88]:
# Scalar Operation
        # in this method you will perform operation on a single matrix and a single number
    
    
# arithmetic 

    # in this case a1 is a matrix and 2 is a scalar

print(a1*2)
print(a1+3)
print(a1/3)


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]]


In [90]:

# relational

print(a2>15)
print(a2==15)
print(a2<=15)
print(a2<15)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False  True]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[[ True  True  True False]
 [False False False False]
 [False False False False]]


In [91]:
# Vector operations
    # when you are perform operation on two numpy array

# arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [92]:
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

In [93]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [94]:
a1==a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [95]:
a1<a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## max/min/sum/prod

In [14]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[27., 30., 61.],
       [61., 60., 52.],
       [47., 45., 58.]])

In [15]:
# max/min/sum/prod
np.max(a1)

61.0

In [16]:
np.min(a1)

27.0

In [17]:
np.prod(a1)

1153553252904000.0

In [18]:
# it give you the max element of each row
# axis 0--> col   1--> row

np.max(a1,axis=1)

array([61., 61., 58.])

In [19]:
# it give you the max element of each column


np.max(a1,axis=0)

array([61., 60., 61.])

In [20]:
np.prod(a1,axis=1)

array([ 49410., 190320., 122670.])

In [21]:
np.min(a1,axis=1)

array([27., 52., 45.])

## mean/median/std/var

In [22]:
# mean/median/std/var

np.mean(a1)

49.0

In [23]:
# here you can also use the parameter axis(1 or 0)

np.mean(a1,axis=1)

array([39.33333333, 57.66666667, 50.        ])

In [24]:
np.median(a1)

52.0

In [25]:
np.std(a1)

12.310790208412925

In [26]:
np.std(a1,axis=0)

array([13.95229969, 12.24744871,  3.74165739])

## trignometric function

In [27]:
np.sin(a1)

array([[ 0.95637593, -0.98803162, -0.96611777],
       [-0.96611777, -0.30481062,  0.98662759],
       [ 0.12357312,  0.85090352,  0.99287265]])

In [28]:
np.cos(a2)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

## Dot product

In [29]:
a2=np.arange(12).reshape(3,4)        # 3x4
a3=np.arange(12).reshape(4,3)        # 4x3

# here you will check if the inner value are same 3x4 4x3 in this case the inner element are same both are 4
# then dot product is possible  and the outer element are the size of the resultant 

print(np.dot(a2,a3))

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


##  Log  and exponents

In [30]:
np.log(a1)

array([[3.29583687, 3.40119738, 4.11087386],
       [4.11087386, 4.09434456, 3.95124372],
       [3.8501476 , 3.80666249, 4.06044301]])

In [31]:
np.exp(a1)

array([[5.32048241e+11, 1.06864746e+13, 3.10429794e+26],
       [3.10429794e+26, 1.14200739e+26, 3.83100800e+22],
       [2.58131289e+20, 3.49342711e+19, 1.54553894e+25]])

In [43]:
# round / floor / ceil


z =np.round(np.random.random(20)*100,4)
z

array([23.3909, 68.7054,  3.4877, 78.7007,  2.8657, 49.312 , 56.0947,
       39.6629, 45.2427, 59.0489, 37.7473,  8.6045,  8.1849, 37.0667,
       17.6716, 92.3334, 98.5119,  6.8865, 98.8779, 46.0009])

In [45]:
# np.floor(np.random.random(20)*100,4)

# or

np.floor(z)

array([23., 68.,  3., 78.,  2., 49., 56., 39., 45., 59., 37.,  8.,  8.,
       37., 17., 92., 98.,  6., 98., 46.])

In [44]:
# np.ceil(np.random.random(20)*100,4)

# or

np.ceil(z)

array([24., 69.,  4., 79.,  3., 50., 57., 40., 46., 60., 38.,  9.,  9.,
       38., 18., 93., 99.,  7., 99., 47.])

### Indexing  and Slicing

In [47]:
a1= np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [54]:
# indexing
#         In indexing you can only fetch one item at a time 

a1[-1]

9

In [55]:
a1[0]

0

In [56]:
a1[5]

5

In [57]:
#2d array

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a2[1,2]

6

In [59]:
a2[2,3]

11

In [60]:
a2[1,0]

4

In [61]:
# 3D tensor printing

In [62]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
# first think that how many 2d are inside the 3d and also in each 2d how many 1d present

# Syntax 
# Array_name[index_number_of_2d , index_number_of_row , index_number_of_column]
# print 5 
a3[1,0,1]


5

In [66]:
a =np.arange(16).reshape(2,2,2,2)
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [67]:
# printing 11 
a[1,0,1,1]

11

In [68]:
# print 6
a[0,1,1,0]

6

In [69]:
a[1,1,0,0]

12

In [74]:
# 4D example indexing
four_d =np.arange(81).reshape(3,3,3,3)
four_d

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [75]:
# print 49 
four_d[1,2,1,1]

49

In [76]:
# print 77
four_d[2,2,1,2]

77

## slicing 
 ##### in slicing you can fetch more than one item at once / at a time

In [77]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# to fetch 2,3,4

a1[2:5]

array([2, 3, 4])

In [85]:
# to fetch 9,8,7
a1[7:]

array([7, 8, 9])

In [86]:
# 2d slicing
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
# slice first row
a2[0,:]
# or[ 0,  1,  2, 
a2[0]

array([0, 1, 2, 3])

In [88]:
a2[1]

array([4, 5, 6, 7])

In [93]:
# for 2nd column
a2[:,1]

array([1, 5, 9])

In [94]:
a2[:,2]

array([ 2,  6, 10])

In [96]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [97]:
a2[:2,:2]

array([[0, 1],
       [4, 5]])

In [99]:
# for 0,3 and 8,11
# you need alternate rows
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [100]:
# 0,2 & 8 and 10

a2[::2,::2]

array([[ 0,  2],
       [ 8, 10]])

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [109]:
a2[1,::3]

array([4, 7])

In [110]:
# 1,2,3 and 5,6,7

a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [113]:
# slicing in case of 3d

a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [116]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
a3[0,1]

array([3, 4, 5])

In [118]:
a3[1,:,1]

array([10, 13, 16])

In [119]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [121]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [122]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [126]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [128]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [132]:
# for each element
# np.nditer()     it convert the array in to one dimention then apply loop on it
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshape

In [133]:
# reshape
# transpose
# ravel

In [134]:
# reshape fucntion we already studied

In [135]:
#transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [137]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [138]:
# ravel()
    # method convert every array into one d no matter how many dimention the aray is

a3.ravel()



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [139]:
# horizontal stacking
# vertical Stacking

In [142]:
# horzontal stacking

a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [143]:
# vertical stacking

np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [144]:
np.hstack((a1,a2,a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

## Spliting

In [146]:
# is a opposite of stacking

# horizontal splitting
print(a1)
np.hsplit(a1,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [148]:
np.vsplit(a2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]