In [1]:
import numpy as np

## np.sort
#### return a sorted copy of an array

In [4]:
# why we not use sorted() method of python because it give us an python list 
# while instead of sorted we use np.sort() method it give us a numpy array

In [5]:
a = np.random.randint(1,100,15)
a

array([ 9, 60, 27, 35, 97, 46, 41, 64,  7,  4, 60, 29, 54, 85, 82])

In [22]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[46, 32, 51, 94],
       [71, 70, 29, 38],
       [37, 32, 66, 72],
       [49, 36, 20, 84],
       [46, 32, 94, 65],
       [23, 24, 78, 68]])

In [7]:
# np.sort()
np.sort(a)

array([ 4,  7,  9, 27, 29, 35, 41, 46, 54, 60, 60, 64, 82, 85, 97])

In [9]:
np.sort(a)

array([ 4,  7,  9, 27, 29, 35, 41, 46, 54, 60, 60, 64, 82, 85, 97])

##  For row wise sorting axis =1 
## For column wise sorting axis =0

In [12]:
np.sort(b)    # row wise sort  axis =1

array([[40, 47, 74, 85],
       [ 6, 16, 82, 95],
       [20, 21, 55, 58],
       [ 2, 23, 25, 28],
       [24, 41, 82, 94],
       [ 2, 80, 86, 95]])

In [13]:
np.sort(b,axis=0)

array([[ 2, 16,  2, 20],
       [47, 23,  6, 25],
       [55, 41, 21, 80],
       [82, 58, 24, 85],
       [82, 74, 28, 94],
       [95, 86, 40, 95]])

In [14]:
# if we want to sort in descending order 
np.sort(a)[::-1]

array([97, 85, 82, 64, 60, 60, 54, 46, 41, 35, 29, 27,  9,  7,  4])

In [15]:
np.sort(b)[::-1]

array([[ 2, 80, 86, 95],
       [24, 41, 82, 94],
       [ 2, 23, 25, 28],
       [20, 21, 55, 58],
       [ 6, 16, 82, 95],
       [40, 47, 74, 85]])

## np.append()

### The numpy.append() appends values along the mentioned axis at the end of the array

In [16]:
np.append(a,555)

array([  9,  60,  27,  35,  97,  46,  41,  64,   7,   4,  60,  29,  54,
        85,  82, 555])

In [17]:
np.append(a,[2,3,4])

array([ 9, 60, 27, 35, 97, 46, 41, 64,  7,  4, 60, 29, 54, 85, 82,  2,  3,
        4])

In [34]:
np.append(b,np.ones((b.shape[0],1)),axis =1)

array([[47., 74., 40., 85.,  1.],
       [82., 16.,  6., 95.,  1.],
       [55., 58., 21., 20.,  1.],
       [ 2., 23., 28., 25.,  1.],
       [82., 41., 24., 94.,  1.],
       [95., 86.,  2., 80.,  1.]])

a.shape

In [31]:
np.ones((b.shape[0],1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [36]:
ar = np.arange(12).reshape(4,3)
ar

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
np.append(ar,np.random.random((ar.shape[0],2)),axis=1)

array([[ 0.        ,  1.        ,  2.        ,  0.29052279,  0.58116643],
       [ 3.        ,  4.        ,  5.        ,  0.15412982,  0.44081298],
       [ 6.        ,  7.        ,  8.        ,  0.85962395,  0.90989645],
       [ 9.        , 10.        , 11.        ,  0.22592758,  0.25289216]])

In [43]:
z = np.zeros((4,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.append(z,np.ones((1,z.shape[0])),axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [46]:
np.append(z,np.ones((3,z.shape[0])),axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.concatinate()

In [47]:
# numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [51]:
c= np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)


np.concatenate((c,d),axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [57]:
f = np.arange(20).reshape(2,10)
g = np.arange(40,60).reshape(2,10)

print(f)
print(g)

np.concatenate((f,g),axis = 0)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [56]:
np.concatenate((f,g),axis =1 )

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

## np.unique()

In [4]:
# it give you the unique array of numbers by removing the repeated elements

e = np.array([3,2,3,4,5,5,4,3,4,67,7,8])
p=np.unique(e)
print(p)

[ 2  3  4  5  7  8 67]


## np.expand_dims
#### with this method we can get the expanded dimentions of an array

In [8]:
# if you have 1d array then you can convert it to 2d with the expand_dims() and if you have 2d array to convet it to 3d array



np.expand_dims(p,axis=0)

array([[ 2,  3,  4,  5,  7,  8, 67]])

In [9]:
np.expand_dims(p,axis=1)

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 7],
       [ 8],
       [67]])

## np.where()
### it return the indices of elements in an input array where the given condition is satisfied

In [10]:
p

array([ 2,  3,  4,  5,  7,  8, 67])

In [12]:
# if we need the index position of those elements which are > 3 (any condition)
np.where(p>3)

(array([2, 3, 4, 5, 6], dtype=int64),)

In [4]:
a=np.random.randint(1,100,15)
a

array([19, 11, 56, 26, 44,  3, 14, 11, 43, 39, 32, 62, 43, 47, 91])

In [14]:
np.where(a>50)   # it give the index of those elemnets which satisfy the condition

(array([ 0,  1,  2,  6,  9, 10, 12], dtype=int64),)

In [15]:
# Another use of this function to replace some values that satisfiy condition or not satisfy np.where(condtion,true,false)


np.where(a>50,0,a)

array([ 0,  0,  0,  4, 35, 24,  0, 33, 18,  0,  0, 37,  0, 48,  7])

In [17]:
np.where(a<50,a,1)

array([ 1,  1,  1,  4, 35, 24,  1, 33, 18,  1,  1, 37,  1, 48,  7])

In [18]:
# replace even number with 0

np.where(a%2==0,0,a)

array([ 0,  0, 89,  0, 35,  0, 69, 33,  0, 87, 77, 37,  0,  0,  7])

## np.argmax
##### it give you the index position of max value

In [19]:
# it give you the index of max value
np.argmax(a)

12

In [20]:
# it give you the index of min value
np.argmin(a)

3

## np.cumsum
### it is used when we want to compute the cumulative sum of array elements over a given axis

In [21]:
np.cumsum(a)

array([ 70, 146, 235, 239, 274, 298, 367, 400, 418, 505, 582, 619, 711,
       759, 766], dtype=int32)

In [25]:
b

array([[46, 32, 51, 94],
       [71, 70, 29, 38],
       [37, 32, 66, 72],
       [49, 36, 20, 84],
       [46, 32, 94, 65],
       [23, 24, 78, 68]])

In [24]:
np.cumsum(b,axis=0) # column wise

array([[ 46,  32,  51,  94],
       [117, 102,  80, 132],
       [154, 134, 146, 204],
       [203, 170, 166, 288],
       [249, 202, 260, 353],
       [272, 226, 338, 421]], dtype=int32)

In [26]:
np.cumsum(b,axis =1) # row wise

array([[ 46,  78, 129, 223],
       [ 71, 141, 170, 208],
       [ 37,  69, 135, 207],
       [ 49,  85, 105, 189],
       [ 46,  78, 172, 237],
       [ 23,  47, 125, 193]], dtype=int32)

## np.cumprod()
#### it can only used for cumeletive product 

In [27]:
np.cumprod(a)

array([         70,        5320,      473480,     1893920,    66287200,
        1590892800, -1897546496,  1805475072, -1861187072,  1285481984,
         197864960, -1268931072,  -777541632,  1332707328,   739016704],
      dtype=int32)

In [28]:
np.cumprod(b)

array([         46,        1472,       75072,     7056768,   501030528,
         712398592,  -815277312,  -915766784,   476367360, -1936113664,
        1065517056,  -592183296,  1047789568,  -934281216, -1505755136,
       -1929379840,  1442840576, -1073741824, -2147483648, -2147483648,
       -2147483648,           0,           0,           0], dtype=int32)

In [29]:
np.cumprod(b,axis=1)

array([[     46,    1472,   75072, 7056768],
       [     71,    4970,  144130, 5476940],
       [     37,    1184,   78144, 5626368],
       [     49,    1764,   35280, 2963520],
       [     46,    1472,  138368, 8993920],
       [     23,     552,   43056, 2927808]], dtype=int32)

## np.percentile()

### is used to compute the nth percentile of the given data(array elements ) along the specified axis

In [30]:
np.percentile(a,100)   # 100 percentile mean that no one is achieve greater marks than that 

92.0

In [31]:
np.percentile(a,50)  # this mean half are greater and half are less

48.0

## np.histrogram
### it represents the frequency of data distribution in the graphical form

In [33]:
a

array([70, 76, 89,  4, 35, 24, 69, 33, 18, 87, 77, 37, 92, 48,  7])

In [32]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])



(array([2, 1, 1, 3, 1, 0, 1, 3, 2, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef()
#### this function tell you that between two quantities what is the relation and by changing one how the other change

In [3]:
salary = np.array([2000,30000,50000])
experience = np.array([1,3,2])

np.corrcoef(salary,experience)

array([[1.        , 0.58065133],
       [0.58065133, 1.        ]])

## isin()
### isin function search multiple item in an array and tell wheather it contain in array or not

In [5]:
a

array([19, 11, 56, 26, 44,  3, 14, 11, 43, 39, 32, 62, 43, 47, 91])

In [9]:
items=[2,11,5,44,3,22]

In [10]:
np.isin(a,items)

array([False,  True, False, False,  True,  True, False,  True, False,
       False, False, False, False, False, False])

## np.flip()
### it can flip the items that are present in the array but can't change the shape

In [12]:
print(a)
np.flip(a)

[19 11 56 26 44  3 14 11 43 39 32 62 43 47 91]


array([91, 47, 43, 62, 32, 39, 43, 11, 14,  3, 44, 26, 56, 11, 19])

## np.put()

##### it is used to change some particular items or numbers

In [13]:
a

array([19, 11, 56, 26, 44,  3, 14, 11, 43, 39, 32, 62, 43, 47, 91])

In [14]:
# syntax np.put(array_name,[item index ][new items])

np.put(a,[0,1],[111,111])     # it change the items parmently 

In [15]:
a

array([111, 111,  56,  26,  44,   3,  14,  11,  43,  39,  32,  62,  43,
        47,  91])

## np.delete()

In [16]:
a

array([111, 111,  56,  26,  44,   3,  14,  11,  43,  39,  32,  62,  43,
        47,  91])

In [17]:
np.delete(a,0)

array([111,  56,  26,  44,   3,  14,  11,  43,  39,  32,  62,  43,  47,
        91])

In [18]:
np.delete(a,[0,1,2])

array([26, 44,  3, 14, 11, 43, 39, 32, 62, 43, 47, 91])

## Set Functions
#### np.union1d
#### np.intersect1d
#### np.setdiff1d
#### np.setxor1d
#### np.in1d
#### np.intersect1d




In [19]:
m= np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
np.intersect1d(m,n)

array([3, 4, 5])

In [21]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [22]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

In [23]:
np.setdiff1d(m,n)

array([1, 2])

## np.clip()

In [26]:
print(a)
np.clip(a,a_min=20,a_max=30)

[111 111  56  26  44   3  14  11  43  39  32  62  43  47  91]


array([30, 30, 30, 26, 30, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30])